services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: klinikai
      POSTGRES_USER: klinikaidb
      POSTGRES_PASSWORD: klinikai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: