# Generated by Django 5.2.11 on 2026-02-19 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('disease', 'Kasallik'), ('symptom', 'Alomat'), ('treatment', 'Davolash'), ('medicine', 'Dori'), ('prevention', 'Profilaktika'), ('general', 'Umumiy')], max_length=20, verbose_name='Kategoriya')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name="To'liq mazmun")),
                ('keywords', models.TextField(help_text='Vergul bilan ajrating: qandli diabet, qon shakar, insulin', verbose_name="Kalit so'zlar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Tibbiy Bilim',
                'verbose_name_plural': 'Tibbiy Bilimlar Bazasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yangi suhbat', max_length=200, verbose_name='Sarlavha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI Suhbat',
                'verbose_name_plural': 'AI Suhbatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI Yordamchi')], max_length=10, verbose_name='Kim yozgan')),
                ('content', models.TextField(verbose_name='Xabar matni')),
                ('sources', models.JSONField(blank=True, default=list, help_text="Qaysi bazadagi ma'lumotlar ishlatilgan", verbose_name='Manbalar')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Ishlatilingan tokenlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'AI Xabar',
                'verbose_name_plural': 'AI Xabarlar',
                'ordering': ['created_at'],
            },
        ),
    ]
