# Generated by Django 5.2.11 on 2026-02-19 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('slug', models.SlugField(blank=True, editable=False, help_text="Avtomatik yaratiladi. URL'da ishlatiladi.", max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('came_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan vaqti')),
                ('reason', models.CharField(max_length=200, verbose_name='Kelish sababi')),
                ('complaint', models.TextField(blank=True, default='', verbose_name='Shikoyat')),
                ('examination', models.TextField(blank=True, default='', verbose_name='Korik natijasi')),
                ('general_note', models.TextField(blank=True, default='', verbose_name='Umumiy izoh')),
            ],
            options={
                'verbose_name': 'Qabul holati',
                'verbose_name_plural': 'Qabul holatlari',
                'ordering': ['-came_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('disease_name', models.CharField(max_length=200, verbose_name='Kasallik nomi')),
                ('icd10', models.CharField(blank=True, default='', max_length=16, verbose_name='ICD-10 kodi')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy tashxis')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='daftar.encounter', verbose_name='Qabul holati')),
            ],
            options={
                'verbose_name': 'Tashxis',
                'verbose_name_plural': 'Tashxislar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('slug', models.SlugField(blank=True, editable=False, help_text="Avtomatik yaratiladi. URL'da ishlatiladi.", max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('card_number', models.CharField(max_length=32, unique=True, verbose_name='Daftarcha raqami')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefon raqam')),
                ('blood_group', models.CharField(blank=True, default='', max_length=3, verbose_name='Qon guruhi')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to=settings.AUTH_USER_MODEL, verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Tibbiy daftarcha',
                'verbose_name_plural': 'Tibbiy daftarchalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='daftar.medicalcard', verbose_name='Tibbiy daftarcha'),
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=150, verbose_name='Kasallik nomi')),
                ('diagnosed_at', models.DateField(blank=True, null=True, verbose_name='Aniqlangan sana')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='Holati')),
                ('note', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='daftar.medicalcard', verbose_name='Tibbiy daftarcha')),
            ],
            options={
                'verbose_name': 'Surunkali kasallik',
                'verbose_name_plural': 'Surunkali kasalliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('allergen', models.CharField(max_length=150, verbose_name='Allergen')),
                ('reaction', models.CharField(blank=True, default='', max_length=255, verbose_name='Reaksiya')),
                ('severity', models.CharField(blank=True, default='', max_length=50, verbose_name='Ogirlik darajasi')),
                ('noted_at', models.DateField(blank=True, null=True, verbose_name='Qayd etilgan sana')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='daftar.medicalcard', verbose_name='Tibbiy daftarcha')),
            ],
            options={
                'verbose_name': 'Allergiya',
                'verbose_name_plural': 'Allergiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('note', models.TextField(blank=True, default='', verbose_name='Umumiy korsatma')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_prescriptions', to='daftar.encounter', verbose_name='Qabul holati')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('medication_name', models.CharField(max_length=150, verbose_name='Dori nomi')),
                ('dosage', models.CharField(blank=True, default='', max_length=100, verbose_name='Doza')),
                ('frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='Qabul qilish tezligi')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='Davomiyligi (kun)')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daftar.prescription', verbose_name='Retsept')),
            ],
            options={
                'verbose_name': 'Retsept bandi',
                'verbose_name_plural': 'Retsept bandlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('came_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan vaqti')),
                ('vaccine_name', models.CharField(max_length=150, verbose_name='Vaksina nomi')),
                ('dose', models.CharField(blank=True, default='', max_length=50, verbose_name='Doza')),
                ('lot_number', models.CharField(blank=True, default='', max_length=80, verbose_name='Partiya raqami')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='daftar.medicalcard', verbose_name='Tibbiy daftarcha')),
            ],
            options={
                'verbose_name': 'Vaksina yozuvi',
                'verbose_name_plural': 'Vaksina yozuvlari',
                'ordering': ['-came_at'],
            },
        ),
    ]
