# Generated by Django 5.2.11 on 2026-02-19 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='profile',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
            preserve_default=False,
        ),
    ]
