# Generated by Django 5.2.11 on 2026-02-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('daftar', '0002_remove_medicalcard_profile_medicalcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='patient_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='accounts.patientprofile', verbose_name='Bemor profili'),
            preserve_default=False,
        ),
    ]
