# Generated by Django 5.2.11 on 2026-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
