# Generated by Django 5.2.11 on 2026-02-21 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navbat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Paracetamol, Amoxicillin...', max_length=200, unique=True, verbose_name='Nomi')),
                ('generic_name', models.CharField(blank=True, help_text='Tibbiy nomi', max_length=200, verbose_name='Umumiy nomi')),
                ('category', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotik'), ('PAINKILLER', "Og'riq qoldiruvchi"), ('VITAMIN', 'Vitamin'), ('ANTIHISTAMINE', 'Allergiya'), ('ANTIVIRAL', 'Virusga qarshi'), ('ANTIFUNGAL', "Zamburug'ga qarshi"), ('CARDIOVASCULAR', 'Yurak-qon tomir'), ('GASTROINTESTINAL', 'Oshqozon-ichak'), ('RESPIRATORY', 'Nafas olish'), ('NEUROLOGICAL', 'Nerv tizimi'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30, verbose_name='Kategoriya')),
                ('form', models.CharField(choices=[('TABLET', 'Tabletka'), ('CAPSULE', 'Kapsula'), ('SYRUP', 'Sirop'), ('INJECTION', 'Ukol'), ('CREAM', 'Krem'), ('OINTMENT', 'Malham'), ('DROPS', 'Tomchi'), ('SPRAY', 'Sprey'), ('POWDER', 'Kukun'), ('OTHER', 'Boshqa')], default='TABLET', max_length=20, verbose_name='Shakli')),
                ('strength', models.CharField(help_text='500mg, 250ml, 5%...', max_length=100, verbose_name='Kuchi')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Ishlab chiqaruvchi')),
                ('description', models.TextField(blank=True, help_text='Dori haqida qisqacha', verbose_name="Ta'rif")),
                ('usage_instructions', models.TextField(blank=True, help_text='Ovqatdan oldin/keyin, suv bilan...', verbose_name="Foydalanish ko'rsatmasi")),
                ('warnings', models.TextField(blank=True, help_text="Yan ta'sir, ehtiyot choralari", verbose_name='Ogohlantirishlar')),
                ('side_effects', models.TextField(blank=True, verbose_name="Yon ta'sirlar")),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text="So'mda", max_digits=10, verbose_name='Narx')),
                ('requires_prescription', models.BooleanField(default=True, help_text='True = faqat retsept bilan', verbose_name='Retsept kerakmi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar bazasi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Retsept raqami')),
                ('diagnosis', models.CharField(help_text='Qisqacha tashxis', max_length=500, verbose_name='Tashxis')),
                ('notes', models.TextField(blank=True, help_text="Bemor uchun qo'shimcha ko'rsatmalar", verbose_name='Doktor eslatmasi')),
                ('valid_until', models.DateField(help_text='Qachongacha amal qiladi', verbose_name='Yaroqlilik muddati')),
                ('barcode', models.CharField(editable=False, help_text='EAN-13 format', max_length=13, unique=True, verbose_name='Shtrix kod')),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='QR kod')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('DISPENSED', 'Berilgan'), ('EXPIRED', "Muddati o'tgan"), ('CANCELLED', 'Bekor qilindi')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True, verbose_name='Berilgan vaqt')),
                ('dispensed_by', models.CharField(blank=True, max_length=200, verbose_name='Kim berdi (Aptekachi)')),
                ('pharmacy_name', models.CharField(blank=True, max_length=200, verbose_name='Apteka nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='navbat.appointment', verbose_name='Navbat')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='navbat.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='1 tabletka, 5ml...', max_length=200, verbose_name='Dozalash')),
                ('frequency', models.CharField(help_text='Kuniga 3 marta, har 8 soatda...', max_length=200, verbose_name='Necha marta')),
                ('duration', models.CharField(help_text='5 kun, 2 hafta, 1 oy...', max_length=100, verbose_name='Davomiyligi')),
                ('quantity', models.PositiveIntegerField(help_text='Nechta (tabletka, shisha...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdori')),
                ('instructions', models.TextField(blank=True, help_text='Ovqatdan oldin/keyin, suv bilan...', verbose_name="Ko'rsatma")),
                ('special_instructions', models.TextField(blank=True, help_text="Haydovchilikka ta'sir qiladi, alkogol bilan ishlatmang...", verbose_name='Maxsus ogohlantirish')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medication', verbose_name='Dori')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='Retsept')),
            ],
            options={
                'verbose_name': 'Retsept elementi',
                'verbose_name_plural': 'Retsept elementlari',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='prescriptio_prescri_de216a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['barcode'], name='prescriptio_barcode_72583c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['qr_code'], name='prescriptio_qr_code_c2ce58_idx'),
        ),
    ]
