# Generated by Django 5.2.11 on 2026-02-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
    ]
