# Generated by Django 5.2.11 on 2026-02-21 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescription_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medication',
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'verbose_name': 'Dori', 'verbose_name_plural': 'Dorilar'},
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_prescri_de216a_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_barcode_72583c_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_qr_code_c2ce58_idx',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispensed_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacy_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_number',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication_name',
            field=models.CharField(default='nomalum', max_length=200, verbose_name='Dori nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='barcode',
            field=models.CharField(editable=False, max_length=13, unique=True, verbose_name='Shtrix kod'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tashxis'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(help_text='3 kun, 1 hafta...', max_length=100, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(help_text='Kuniga 3 mahal', max_length=100, verbose_name='Necha mahal'),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
