# Generated by Django 5.2.11 on 2026-02-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescriptionitem_medication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Dori nomi')),
                ('price_per_pack', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="1 pachka narxi (so'm)")),
                ('units_per_pack', models.PositiveIntegerField(default=1, help_text='Parasetamol 10talik → 10, Ampula → 1, Shisha → 1', verbose_name='1 pachkada nechta')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('pochka', 'Pochka'), ('ampula', 'Ampula'), ('shisha', 'Shisha'), ('ml', 'Millilitr'), ('gr', 'Gramm')], default='dona', max_length=20, verbose_name='Birlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Dori bazasi',
                'verbose_name_plural': 'Dorilar bazasi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='doses_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='Kuniga necha mahal'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Necha kun'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='pack_unit',
            field=models.CharField(default='dona', max_length=20, verbose_name='Birlik'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Pachka narxi'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, verbose_name='Pachkada nechta dona'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.medication', verbose_name='Dori bazasidan'),
        ),
    ]
