# Generated by Django 5.2.11 on 2026-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_medication_prescriptionitem_doses_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='measure_type',
            field=models.CharField(choices=[('count', 'Sanaladigan'), ('volume', 'Hajmli')], default='count', help_text='Sanaladigan=dona/pachka, Hajmli=shisha/shpris/surtma', max_length=10, verbose_name='Hisoblash turi'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='measure_type',
            field=models.CharField(default='count', max_length=10),
        ),
    ]
