# Generated by Django 5.2.11 on 2026-02-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_medication_measure_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medication_name',
        ),
    ]
