# Generated by Django 5.2.11 on 2026-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_remove_prescriptionitem_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='measure_type',
            field=models.CharField(choices=[('count', 'Sanaladigan'), ('volume', 'Hajmli'), ('injection', 'Ukol/Ampula')], default='count', help_text='Sanaladigan=dona/pachka, Hajmli=shisha/shpris/surtma', max_length=10, verbose_name='Hisoblash turi'),
        ),
    ]
