"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from celery import Celery

from dotenv import load_dotenv
load_dotenv() # .env fileni oqishi uchun



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# =============================================================================

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # xavfli shunday serverga qoyilsa kop malumotlarni olishi mn xakker
# DEBUG = config('DEBUG', default=True, cast=bool)  # bu xavfsiz usuli lekin bunda DOMEN bolishi kerak shunda FALSE deb ishlatsa xavfsiz bo'ladi

# ==============================================================================

ALLOWED_HOSTS = ['*']
# Agarda men domen olsam shuni urlini yozaman va debug False qilaman shunda xavfsiz boladi yani aynan shu urlsdan sorov kelsa qabul boshqadan bolsa javob bermaydi
# CSRF_TRUSTED_ORIGINS = ['https://muhammadsav.uz', 'https://www.muhammadsav.uz']


# =============================================================================

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'drf_yasg',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # BU JWT da logout uchun kerak , ozi shart emas lekin pro va xavfszlik yuqori bolishi uchun kk

    'apps.accounts',          # 1. Birinchi (User model)
    'apps.prescriptions',     # 4. To'rtinchi
    'apps.ai_assistant',
    'apps.daftar',
    'apps.navbat',

]

AUTH_USER_MODEL = 'accounts.User'


# GEMINI API KEY .ENV FILEDAN
GEMINI_API_KEY=os.environ.get('GEMINI_API_KEY')

if not GEMINI_API_KEY:
    print("⚠️ WARNING: GEMINI_API_KEY topilmadi!")


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://localhost:5174",
#     "http://127.0.0.1:5173",
#     "http://127.0.0.1:5174",
# ]
# CORS_ALLOW_CREDENTIALS = True
#




ROOT_URLCONF = 'config.urls'

 # ====================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#



DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.postgresql',
        'NAME':os.environ.get('DB_NAME'),
        'USER':os.environ.get('DB_USER'),
        'PASSWORD':os.environ.get('DB_PASSWORD'),
        'HOST':os.environ.get('DB_HOST'),
        'PORT':os.environ.get('DB_PORT'),
    },
}





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# BOT
TELEGRAM_BOT_TOKEN=os.environ.get("TELEGRAM_BOT_TOKEN")


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =======================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



# Login kodining amal qilish muddati
TELEGRAM_AUTH_EXPIRY_MINUTES = 5
# maksimal urinishlar soni
MAX_LOGIN_ATTEMPTS = 3
# telegram auth ma'lumotlarini avtomatik tozalash vaqti(soatda)
AUTH_CLEANUP_INTERVAL_HOURS = 1


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

# app = Celery('store')
# app.config_from_object('django.conf:settings', namespace='CELERY')
# app.autodiscover_tasks()

# CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
# CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')




# ----------------------  GEMINI API KEY -------------------
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
GOOGLE_API_KEY = GEMINI_API_KEY




LOGIN_URL = 'auth:login'
LOGIN_REDIRECT_URL = 'dashboard'

SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True


# settings.py

# ... boshqa sozlamalar

# ✅ SWAGGER SOZLAMALARI
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT authorization token. Format: Bearer <token>'
        }
    },
    'USE_SESSION_AUTH': False,  # Session auth o'chirilgan
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}




# ++++++++++++++++++++++++++++++++++++++++++++++++++++++
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++
# JWT SETTINGS
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=4),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',

}




# CORS SETTINGS (Frontend bilan ishlash uchun)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True


import os
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


AI_PROVIDER = 'gemini'
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', default='')

# settings.py
AI_PROVIDER = 'groq'
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', default='')
